refresh_rate: 1 seconds

appenders:
  stdout:
    kind: console

  rest:
    kind: file
    path: "log/rest.log"
    encoder:
      pattern: "{d}.{l} - {m}{n}"

root:
  level: info
  appenders:
    - stdout
    - rest

loggers:
  app::backend::db:
    level: info

  app::requests:
    level: info
    appenders:
      - rest
    additive: false